[default]
SECRET_KEY="JUNIORPXLG"
SQLALCHEMY_TRACK_MODIFICATIONS = false

EXTENSIONS = [
    'mvc_flask:FlaskMVC', 
    'app.ext:init_app'
]

[production]

[development]
SQLALCHEMY_DATABASE_URI = 'sqlite:///development.sqlite'

[testing]
SQLALCHEMY_DATABASE_URI = 'sqlite:///development.sqlite'